POST http://localhost:3000/tags
Content-type: application/json

{
  "name": "javascript",
  "slug": "javascript",
  "description": "JavaScript is a programming language commonly used in web development."
}
